/*
 * File: app/view/TaskForm.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ToDoList.view.TaskForm', {
    extend: 'Ext.form.Panel',

    config: {
        title: 'Task Details',
        itemId: 'taskForm',
        items: [
            {
                xtype: 'fieldset',
                instructions: 'Please complete all fields',
                title: 'Task Details',
                items: [
                    {
                        xtype: 'textfield',
                        label: 'Title',
                        name: 'title',
                        autoCapitalize: true,
                        placeHolder: 'Task title'
                    },
                    {
                        xtype: 'textareafield',
                        label: 'Details',
                        name: 'description',
                        autoCapitalize: true,
                        placeHolder: 'Task details'
                    },
                    {
                        xtype: 'togglefield',
                        label: 'Done',
                        name: 'completed'
                    },
                    {
                        xtype: 'datepickerfield',
                        label: 'Field',
                        name: 'dueDate',
                        placeHolder: 'dd/mm/yyyy',
                        dateFormat: 'D d M Y',
                        picker: {
                            slotOrder: [
                                'day',
                                'month',
                                'year'
                            ],
                            yearFrom: 2013,
                            yearTo: 2023
                        }
                    }
                ]
            },
            {
                xtype: 'toolbar',
                docked: 'bottom',
                items: [
                    {
                        xtype: 'button',
                        action: 'deleteTask',
                        ui: 'decline',
                        text: 'Delete'
                    },
                    {
                        xtype: 'spacer'
                    },
                    {
                        xtype: 'button',
                        action: 'saveTask',
                        ui: 'confirm',
                        text: 'Save'
                    }
                ]
            }
        ]
    }

});