/*
 * File: app/store/TaskStore.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ToDoList.store.TaskStore', {
    extend: 'Ext.data.Store',

    requires: [
        'ToDoList.model.Task'
    ],

    config: {
        autoLoad: true,
        autoSync: true,
        model: 'ToDoList.model.Task',
        storeId: 'TaskStore',
        proxy: {
            type: 'localstorage',
            id: 'senchatasks'
        },
        sorters: {
            property: 'dueDate'
        },
        grouper: {
            groupFn: function(record) {
                if (record && record.get('dueDate')) {
                    return record.get("dueDate").toDateString();
                }
            },
            sortProperty: 'dueDate'
        }
    }
});