/*
 * File: app/model/Task.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ToDoList.model.Task', {
    extend: 'Ext.data.Model',

    config: {
        fields: [
            {
                name: 'title',
                type: 'string'
            },
            {
                name: 'completed',
                defaultValue: false,
                type: 'boolean'
            },
            {
                name: 'description',
                type: 'string'
            },
            {
                name: 'dueDate',
                type: 'date'
            }
        ]
    }
});