/*
 * File: app/view/RootNavView.js
 *
 * This file was generated by Sencha Architect version 2.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.1.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ToDoList.view.RootNavView', {
    extend: 'Ext.navigation.View',

    config: {
        autoDestroy: false,
        items: [
            {
                xtype: 'list',
                title: 'To Do List',
                itemId: 'taskList',
                emptyText: '<p class="instructions">No tasks here yet; please touch the button "+" in the toolbar below to make one.<br>If you like this app, buy the book! :) Thanks.</p>',
                itemTpl: [
                    '<div class="task completed_{completed}">{title}</div>'
                ],
                store: 'TaskStore',
                onItemDisclosure: true,
                items: [
                    {
                        xtype: 'toolbar',
                        docked: 'bottom',
                        items: [
                            {
                                xtype: 'spacer'
                            },
                            {
                                xtype: 'button',
                                action: 'createTask',
                                ui: 'plain',
                                iconCls: 'add',
                                iconMask: true
                            }
                        ]
                    }
                ]
            }
        ]
    }

});